### ISSUE TITLE
Update google_maps package version

### ISSUE THREAD

**Issue by zolboo-gtn** [zyzdev/flutter_street_view#37]
Can not used with `google_maps_flutter`.
`google_maps_flutter@latest` depends on `google_maps@7.1.0` while this package is on `google_maps@6.1.0`.

**Comment by liorboyango** [comment]
I updated my fork with latest dependencies, including google_maps 7.1.0:
```yaml
flutter_google_street_view:
   git:
      url: https://github.com/liorboyango/flutter_street_view.git
      path: flutter_google_street_view
      ref: master
```
