### ISSUE TITLE
The screen goes black 

### ISSUE THREAD

**Issue by Santi92** [zyzdev/flutter_street_view#5]
Hello again 👋 

Summary
The screen goes black when it cannot find a view of a location.

flutter doctor
 ``` bash
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, 2.5.1, on macOS 11.2.3 20D91 darwin-x64, locale en-CO)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
[✓] VS Code (version 1.61.2)
[✓] VS Code (version 1.57.0)
[✓] VS Code (version 1.56.2)
[✓] Connected device (2 available)
 ```

pubspec
 ```yaml
 name: xxxxxx
 description: xxxxx
 
 environment:
  sdk: 2.14.2
  flutter: 2.5.1
  
  dependencies:
  flutter:
    sdk: flutter

   flutter_google_street_view: ^2.2.2

 ```
**Steps to Reproduce Issue:**

<img width="369" alt="Screen Shot 2021-10-29 at 2 38 07 PM" src="https://user-images.githubusercontent.com/12769042/139493114-dc11e684-8a2e-4560-a31b-291682ba2b0f.png">

:nerd_face: I have consulted this behavior and it is normal in street view when that location does not yet have mapped, the same thing happens in js SDK. :nerd_face: 

The ideal point is to control this case, I would like to know if from the SDK it can be notified through a listener, to detect this behavior and show the user a corresponding message. :question:
